// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://spcanmrbdzyhbzxpaoiq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNwY2FubXJiZHp5aGJ6eHBhb2lxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ4Njk2MDYsImV4cCI6MjA3MDQ0NTYwNn0.WzL6ZXCkccQvTP8vaE9nISeTaYu8bw3eu6aCXOezWFo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});